Add path to Homebrew binaries

diff --git a/settings/macOS/bash/dot-bashrc_macos b/settings/macOS/bash/dot-bashrc_macos
--- a/settings/macOS/bash/dot-bashrc_macos
+++ b/settings/macOS/bash/dot-bashrc_macos
@@ -1,26 +1,86 @@
 # dot-bashrc_macos
 # ORIGIN: 2019-11-12 by hmr
+# vim: filetype=bash
+
+function HB_ADD_PATH () {
+  [ -z "$1" ] && return 1
+  local HB_TARGET=/usr/local/opt/$1/libexec/gnubin
+  if [ -d ${HB_TARGET} ]; then
+    export PATH=${HB_TARGET}:${PATH}
+    return 0
+  else
+    return 2
+  fi
+}
 
 echo "Processing dot-bashrc_macos"
 echo ${OSTYPE} | grep "darwin" >& /dev/null
 if [ $? -eq 0 ]; then
-  # Bash
+  # BASH
   echo ${SHELL} | grep "bash" >& /dev/null
   if [ $? -eq 0 ]; then
     echo "  Setting variable to suppress deprecation warning for bash."
     export BASH_SILENCE_DEPRECATION_WARNING=1
   fi
+
   # use lesspipe
   which lesspipe.sh >& /dev/null
   if [ $? -eq 0 ]; then
-    echo "  Setting to use lesspipe."
-    export LESSOPEN="|$(which lesspipe.sh) %s"
+    echo "  Setting lesspipe."
+    #export LESSOPEN="|$(which lesspipe.sh) %s"
+    eval $(lesspipe.sh)
   fi
+
   # iTerm2 Shell Integration
   #if [ -e "${HOME}/.iterm2_shell_integration.bash" ]; then
   #  echo "  Setting iTerm2 shell integration."
   #  source ${HOME}/.iterm2_shell_integration.bash
   #fi
+
+  # Android Debug Bridge(adb)
+  echo "  Setting Path to Android development tools."
+  export ANDROID_HOME=${HOME}/Library/Android/sdk
+  export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
+
+  # Use HomeBrew binaries instead of macOS default.
+  # GNU Coreutils
+  TEMP_TGT=coreutils
+  HB_ADD_PATH ${TEMP_TGT} \
+    && echo "  Set path to ${TEMP_TGT}" \
+    || echo "  ${TEMP_TGT} not found"
+
+  # GNU Grep
+  TEMP_TGT=grep
+  HB_ADD_PATH ${TEMP_TGT} \
+    && echo "  Set path to ${TEMP_TGT}" \
+    || echo "  ${TEMP_TGT} not found"
+
+  # GNU Sed
+  TEMP_TGT=gnu-sed
+  HB_ADD_PATH ${TEMP_TGT} \
+    && echo "  Set path to ${TEMP_TGT}" \
+    || echo "  ${TEMP_TGT} not found"
+
+  # GNU Tar
+  TEMP_TGT=gnu-tar
+  HB_ADD_PATH ${TEMP_TGT} \
+    && echo "  Set path to ${TEMP_TGT}" \
+    || echo "  ${TEMP_TGT} not found"
+
+  # GNU Time
+  TEMP_TGT=gnu-time
+  HB_ADD_PATH ${TEMP_TGT} \
+    && echo "  Set path to ${TEMP_TGT}" \
+    || echo "  ${TEMP_TGT} not found"
+
+  # Python3.8
+  if [ -d /usr/local/opt/python@3.8/bin ]; then
+    export PATH="/usr/local/opt/python@3.8/bin:${PATH}"
+    echo "  Set path to Python@3.8"
+  else
+    echo "  python@3.8 not found"
+  fi
+
 else
   echo "  This environment isn't macOS."
 fi
