style(tools): improve modeline and reformat indent

diff --git a/libexec/tools/launch_tmux b/libexec/tools/launch_tmux
--- a/libexec/tools/launch_tmux
+++ b/libexec/tools/launch_tmux
@@ -1,6 +1,6 @@
 #!/usr/bin/env zsh
 
-# vim: set et syn=bash ft=sh ff=unix fenc=utf-8 ts=4 sts=4 sw=4 : # GPP default modeline for shell script
+# vim: set ft=sh syn=bash fenc=utf-8 ff=unix fixeol et sw=2 ts=2 sts=2: #GPP default modeline for shell scripts
 # shellcheck shell=bash disable=SC1091
 
 # Part of GPP
@@ -19,26 +19,26 @@ DRY_RUN=0
 
 # Determine TERM
 if [[ -n $TERM_PROGRAM ]]; then
-    case $TERM_PROGRAM in
-        "ghostty" )
-            TERM="xterm-ghostty";;
-        "rio"     )
-            TERM="xterm-rio";;
-        "iTerm.app" )
-            TERM="xterm-256color-iTerm" ;;
-        "WezTerm" | "Tabby" | "WarpTerminal" | "Hyper" | "waveterm" )
-            TERM="xterm-256color";;
-    esac
+  case $TERM_PROGRAM in
+    "ghostty" )
+      TERM="xterm-ghostty";;
+    "rio"     )
+      TERM="xterm-rio";;
+    "iTerm.app" )
+      TERM="xterm-256color-iTerm" ;;
+    "WezTerm" | "Tabby" | "WarpTerminal" | "Hyper" | "waveterm" )
+      TERM="xterm-256color";;
+  esac
 elif [[ -n $KITTY_PID ]]; then
-    TERM="xterm-kitty"
+  TERM="xterm-kitty"
 elif [[ -n $ALACRITTY_SOCKET ]]; then
-    TERM="alacritty"
+  TERM="alacritty"
 elif [[ $TERMINAL_NAME == "contour" ]]; then
-    TERM="contour"
+  TERM="contour"
 elif [[ -n $electermHost ]]; then
-    TERM="xterm-256color"
+  TERM="xterm-256color"
 else
-    TERM="xterm-256color"
+  TERM="xterm-256color"
 fi
 
 TERM=${TERM_OVERRIDE:-${TERM}}
@@ -52,45 +52,45 @@ TMUX_BIN="${TMUX_BIN_OVERRIDE:-"tmux"}"
 # TMUX_BIN="/Users/hmr/src/tmux/tmux-kkp/tmux"
 
 if [[ ${#TMUX_OPT_OVERRIDE[@]} -eq 0 ]]; then
-    TMUX_OPT=("-l")
+  TMUX_OPT=("-l")
 else
-    TMUX_OPT=("${TMUX_OPT_OVERRIDE[@]}")
+  TMUX_OPT=("${TMUX_OPT_OVERRIDE[@]}")
 fi
 # TMUX_OPT=("-l" "-vv") # tmux debug setting
 
 TMUX_CMD="${TMUX_CMD_OVERRIDE}"
 
 post_processing() {
-    # Logout setting
-    if [[ -r "${ZDOTDIR}/dot-zlogout" ]]; then
-        source "${ZDOTDIR}/dot-zlogout"
-    fi
+  # Logout setting
+  if [[ -r "${ZDOTDIR}/dot-zlogout" ]]; then
+    source "${ZDOTDIR}/dot-zlogout"
+  fi
 }
 
 show_usage() {
-    echo "Usage:"
-    echo "launch_tmux login_info [command]"
-    echo "  login_info is ssh style like 'user@server'"
-    echo "  command is 'auto'(default), 'new' or 'reattach'."
-    echo
+  echo "Usage:"
+  echo "launch_tmux login_info [command]"
+  echo "  login_info is ssh style like 'user@server'"
+  echo "  command is 'auto'(default), 'new' or 'reattach'."
+  echo
 }
 
 generate_sesid() {
-    TMP_SESID=""
+  TMP_SESID=""
 
-    echo "Making session id... "
+  echo "Making session id... "
 
-    if [[ -r /dev/urandom ]]; then
-        # urandom available
-        echo "by /dev/urandom"
-        TMP_SESID=$(dd bs=64 count=1 if=/dev/urandom 2>/dev/null | shasum -b | cut -c1-6)
-    else
-        # urandom not available -> use epoch second
-        echo "by epoch"
-        TMP_SESID=$(dc -e "16o 10i $(date +%s)p" | shasum | cut -c1-6)
-    fi
+  if [[ -r /dev/urandom ]]; then
+    # urandom available
+    echo "by /dev/urandom"
+    TMP_SESID=$(dd bs=64 count=1 if=/dev/urandom 2>/dev/null | shasum -b | cut -c1-6)
+  else
+    # urandom not available -> use epoch second
+    echo "by epoch"
+    TMP_SESID=$(dc -e "16o 10i $(date +%s)p" | shasum | cut -c1-6)
+  fi
 
-    echo "${TMP_SESID}"
+  echo "${TMP_SESID}"
 }
 
 trap 'post_processing' 1 2 3 15
@@ -107,8 +107,8 @@ echo "GPP_HOME=${GPP_HOME}"
 echo "PATH=${PATH}"
 
 if [[ -z ${GPP_HOME} ]]; then
-    echo "\$GPP_HOME isn't set."
-    exit 1
+  echo "\$GPP_HOME isn't set."
+  exit 1
 fi
 
 source "${GPP_HOME}/settings/apps/shell_common/dot-shell_shellenv"
@@ -118,18 +118,18 @@ source "${GPP_HOME}/settings/apps/shell_common/dot-shell_shellenv"
 ZDOTDIR="${HOME}/.config/zsh"
 if [[ -r "${ZDOTDIR}/dot-zprofile_ssh-agent" ]]; then
 
-    echo "Calling dot-(z)profile_ssh-agent..."
-    echo "--------------------------------------------------------------------------------"
-    source "${ZDOTDIR}/dot-zprofile_ssh-agent"
-    echo "--------------------------------------------------------------------------------"
-    SSH_OPT+=("-A")
+  echo "Calling dot-(z)profile_ssh-agent..."
+  echo "--------------------------------------------------------------------------------"
+  source "${ZDOTDIR}/dot-zprofile_ssh-agent"
+  echo "--------------------------------------------------------------------------------"
+  SSH_OPT+=("-A")
 fi
 
 # Check number of args
 if (( $# == 0 )); then
-    echo "Error: Not enough arguments"
-    show_usage
-    exit 1
+  echo "Error: Not enough arguments"
+  show_usage
+  exit 1
 fi
 
 # Set SSH target host
@@ -140,54 +140,54 @@ shift
 CMD_OPT=""
 while (( $# > 0 ))
 do
-    OPT=$1
-    shift
-    case "${OPT}" in
-        "auto" )
-            MODE=${OPT}
-            ;;
+  OPT=$1
+  shift
+  case "${OPT}" in
+    "auto" )
+      MODE=${OPT}
+      ;;
 
-        "new" )
-            MODE=${OPT}
-            ;;
+    "new" )
+      MODE=${OPT}
+      ;;
 
-        "reattach" )
-            MODE=${OPT}
-            ;;
+    "reattach" )
+      MODE=${OPT}
+      ;;
 
-        "dryrun" )
-            DRY_RUN="1"
-            echo "Dry-run mode"
-            ;;
+    "dryrun" )
+      DRY_RUN="1"
+      echo "Dry-run mode"
+      ;;
 
-        "debug" )
-            TMUX_OPT+=(-v)
-            echo "Debug mode. Log file like 'tmux-{server|client}-yyyyy.log' will be generated."
-            SSH_OPT+=("-v")
-            ;;
+    "debug" )
+      TMUX_OPT+=(-v)
+      echo "Debug mode. Log file like 'tmux-{server|client}-yyyyy.log' will be generated."
+      SSH_OPT+=("-v")
+      ;;
 
-        tmux=* )
-            TMUX_BIN="${OPT#*=}"
-            echo "Use ${TMUX_BIN} as tmux."
-            ;;
+    tmux=* )
+      TMUX_BIN="${OPT#*=}"
+      echo "Use ${TMUX_BIN} as tmux."
+      ;;
 
-		term=* )
-			TERM="${OPT#*=}"
-			echo "TERM was overridden by '${TERM}'."
-			;;
+    term=* )
+      TERM="${OPT#*=}"
+      echo "TERM was overridden by '${TERM}'."
+      ;;
 
-        *)
-            CMD_OPT="${CMD_OPT} ${OPT}"
-            ;;
-    esac
+    *)
+      CMD_OPT="${CMD_OPT} ${OPT}"
+      ;;
+  esac
 done
 
 
 
 # Check SSH Agent
 if (( ${SSH_AGENT_PID:-0} == 0 )); then
-    echo "SSH Agent isn't configured."
-    #exit 1
+  echo "SSH Agent isn't configured."
+  #exit 1
 fi
 
 
@@ -206,87 +206,87 @@ fi
 
 # Tmux's Session ID processing("reattach" or "auto" mode only)
 if [[ $MODE == reattach || $MODE == auto ]]; then
-    echo "MODE: ${MODE}"
-    # Get the Tmux session ID from already existing session.
-    # local
-    if [[ $TRGT_HOST == localhost ]]; then
-        # Local
-        echo "SESID=\$(${TMUX_BIN} ls 2>&1 | sort -n -r -k 2 | head -n 1 | cut -c1-6 | tr -d \"\\\n\")"
-        SESID=$(${TMUX_BIN} ls 2>&1 | sort -n -r -k 2 | head -n 1 | cut -c1-6 | tr -d "\n")
-    else
-        # Remote
-        echo "SESID=\$(${SSH_BIN} ${SSH_OPT[*]} \"${TRGT_HOST}\" \"${TMUX_BIN}\" ls 2> /dev/null | sort -n -r -k 2 | head -n 1)"
-        SESID=$("${SSH_BIN}" "${SSH_OPT[@]}" "${TRGT_HOST}" "${TMUX_BIN}" ls 2> /dev/null | sort -n -r -k 2 | head -n 1)
-		echo "SESID='${SESID}'"
-    fi
+  echo "MODE: ${MODE}"
+  # Get the Tmux session ID from already existing session.
+  # local
+  if [[ $TRGT_HOST == localhost ]]; then
+    # Local
+    echo "SESID=\$(${TMUX_BIN} ls 2>&1 | sort -n -r -k 2 | head -n 1 | cut -c1-6 | tr -d \"\\\n\")"
+    SESID=$(${TMUX_BIN} ls 2>&1 | sort -n -r -k 2 | head -n 1 | cut -c1-6 | tr -d "\n")
+  else
+    # Remote
+    echo "SESID=\$(${SSH_BIN} ${SSH_OPT[*]} \"${TRGT_HOST}\" \"${TMUX_BIN}\" ls 2> /dev/null | sort -n -r -k 2 | head -n 1)"
+    SESID=$("${SSH_BIN}" "${SSH_OPT[@]}" "${TRGT_HOST}" "${TMUX_BIN}" ls 2> /dev/null | sort -n -r -k 2 | head -n 1)
+    echo "SESID='${SESID}'"
+  fi
 
     # Error check
     case "${SESID}" in
-        "server exited unexpectedly" )
-            echo "It looks some kind of error happens on the server."
-            exit 1
-            ;;
-        bash:* | zsh:* ) # bash: line 1: tmux: command not found
-            echo "Tmux hasn't been installed into the target host."
-            exit 1
-            ;;
-		"missing or unsuitable terminal:"* )
-			echo "TERM='${TERM}' isn't exist on target host."
-			exit 1
-			;;
-        * )
-            echo "Error check passed."
-            ;;
+      "server exited unexpectedly" )
+        echo "It looks some kind of error happens on the server."
+        exit 1
+        ;;
+      bash:* | zsh:* ) # bash: line 1: tmux: command not found
+        echo "Tmux hasn't been installed into the target host."
+        exit 1
+        ;;
+      "missing or unsuitable terminal:"* )
+        echo "TERM='${TERM}' isn't exist on target host."
+        exit 1
+        ;;
+      * )
+        echo "Error check passed."
+        ;;
     esac
 
     if echo "${SESID}" | ggrep -Pq "[^:]+?: \d+ "; then
-        SESID=$(echo "${SESID}" | cut -d ":" -f 1)
+      SESID=$(echo "${SESID}" | cut -d ":" -f 1)
     else
-        SESID=$(echo "${SESID}" | cut -c 1-6)
+      SESID=$(echo "${SESID}" | cut -c 1-6)
     fi
 
     echo "SESID='${SESID}'"
     case "${SESID}" in
-        # Failed to get already existing session id.
-        "no ser"* | "no cur"* | "error "* | "server"* | "" )
-            # Session ID generation
-            # SESID=$(generate_sesid)
-            # CMD_OPT="${CMD_OPT} -s ${SESID}"
+      # Failed to get already existing session id.
+      "no ser"* | "no cur"* | "error "* | "server"* | "" )
+      # Session ID generation
+      # SESID=$(generate_sesid)
+      # CMD_OPT="${CMD_OPT} -s ${SESID}"
 
-            if [[ $MODE == auto ]]; then
-                TMUX_CMD="new-session"
-            else
-                # "reattach" mode
-                echo "Error: The session to reattach not found."
-                exit 1
-            fi
-            ;;
+      if [[ $MODE == auto ]]; then
+        TMUX_CMD="new-session"
+      else
+        # "reattach" mode
+        echo "Error: The session to reattach not found."
+        exit 1
+      fi
+      ;;
 
-        * )
-            TMUX_CMD="attach-session"
-            if [[ $TRGT_HOST == localhost ]]; then
-                CMD_OPT="${CMD_OPT} -t ${SESID}"
-            else
-                CMD_OPT="${CMD_OPT} -t '=${SESID}'"
-            fi
-    esac
+    * )
+      TMUX_CMD="attach-session"
+      if [[ $TRGT_HOST == localhost ]]; then
+        CMD_OPT="${CMD_OPT} -t ${SESID}"
+      else
+        CMD_OPT="${CMD_OPT} -t '=${SESID}'"
+      fi
+  esac
 elif [[ $MODE == new ]]; then
-    TMUX_CMD="new-session"
+  TMUX_CMD="new-session"
 else
-    echo "Error: Failed to determine mode. Choose 'auto' 'new' 'reattach'"
+  echo "Error: Failed to determine mode. Choose 'auto' 'new' 'reattach'"
 fi
 
 # Connect to local or remote host and launch tmux
 case ${TRGT_HOST} in
-    localhost )
-        echo "${TMUX_BIN} ${TMUX_OPT[*]} ${TMUX_CMD} ${CMD_OPT}"
-        (( DRY_RUN == 0 )) &&
-            "${TMUX_BIN}" "${TMUX_OPT[@]}" "${TMUX_CMD}"
-        ;;
+  localhost )
+    echo "${TMUX_BIN} ${TMUX_OPT[*]} ${TMUX_CMD} ${CMD_OPT}"
+    (( DRY_RUN == 0 )) &&
+      "${TMUX_BIN}" "${TMUX_OPT[@]}" "${TMUX_CMD}"
+    ;;
 
-    * )
-        echo "${SSH_BIN} ${SSH_OPT[*]} ${TRGT_HOST} ${TMUX_BIN} ${TMUX_OPT[*]} ${TMUX_CMD} ${CMD_OPT:-}"
-        (( DRY_RUN == 0 )) &&
-            "${SSH_BIN}" "${SSH_OPT[@]}" "${TRGT_HOST}" "${TMUX_BIN}" "${TMUX_OPT[@]}" "${TMUX_CMD}" "${CMD_OPT:-}"
-        ;;
+  * )
+    echo "${SSH_BIN} ${SSH_OPT[*]} ${TRGT_HOST} ${TMUX_BIN} ${TMUX_OPT[*]} ${TMUX_CMD} ${CMD_OPT:-}"
+    (( DRY_RUN == 0 )) &&
+      "${SSH_BIN}" "${SSH_OPT[@]}" "${TRGT_HOST}" "${TMUX_BIN}" "${TMUX_OPT[@]}" "${TMUX_CMD}" "${CMD_OPT:-}"
+    ;;
 esac
diff --git a/libexec/tools/netlocd b/libexec/tools/netlocd
--- a/libexec/tools/netlocd
+++ b/libexec/tools/netlocd
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# vim: set noet syn=bash ft=sh ff=unix fenc=utf-8 ts=2 sw=0 : # GPP default modeline for bash script
+# vim: set ft=sh syn=bash fenc=utf-8 ff=unix fixeol et sw=2 ts=2 sts=2: #GPP default modeline for shell scripts
 # shellcheck shell=bash disable=SC1091,SC2155,SC3010,SC3021,SC3037 source=${GPP_HOME}
 
 # netlocd: switch macOS network location by SSID/BSSID.
@@ -34,9 +34,9 @@ WIFI_DEV="$(eval networksetup -listallhardwareports | awk '/^Hardware Port: (Wi-
 DEFAULT_LOCATION="Automatic"
 POLL_INTERVAL_SEC=5
 CHECK_SSID_COMMANDS=(\
-	"ipconfig getsummary ${WIFI_DEV} | grep -E 'SSID|BSSID' | sed -e 's/^ *//' -e 's/ : /:/'" \
-	"ioreg -d 1 -f -r -c 'AirPort_BrcmNIC_Interface' | grep -E 'IO80211SSID|IO80211BSSID' | sed -e 's/[ \|\"]//g' -e 's/IO80211//g' -e 's/=/:/g'" \
-	"${GPP_HOME}/libexec/tools/GetBSSID.app/Contents/MacOS/GetBSSID" \
+  "ipconfig getsummary ${WIFI_DEV} | grep -E 'SSID|BSSID' | sed -e 's/^ *//' -e 's/ : /:/'" \
+  "ioreg -d 1 -f -r -c 'AirPort_BrcmNIC_Interface' | grep -E 'IO80211SSID|IO80211BSSID' | sed -e 's/[ \|\"]//g' -e 's/IO80211//g' -e 's/=/:/g'" \
+  "${GPP_HOME}/libexec/tools/GetBSSID.app/Contents/MacOS/GetBSSID" \
 )
 CHECK_SSID_COMMAND=""
 
@@ -67,14 +67,14 @@ GET_WIFI_SUMMARY() {
   local line ssid="" bssid=""
   # shellcheck disable=SC2016
   while IFS= read -r line; do
-		# LOG "LINE: ${line}"
+    # LOG "LINE: ${line}"
     case "$line" in
       SSID:*)  ssid="${line#SSID:}";;
       BSSID:*) bssid="${line#BSSID:}";;
     esac
   done < <(eval "${CHECK_SSID_COMMAND}")
-	# LOG "SSID=$ssid"
-	# LOG "BSSID=$bssid"
+  # LOG "SSID=$ssid"
+  # LOG "BSSID=$bssid"
   # Trim spaces
   # ssid="${ssid#"${ssid%%[![:space:]]*}"}"; ssid="${ssid%"${ssid##*[![:space:]]}"}"
   # bssid="${bssid#"${bssid%%[![:space:]]*}"}"; bssid="${bssid%"${bssid##*[![:space:]]}"}"
@@ -95,10 +95,10 @@ SWITCH_LOCATION() {
     return 0
   fi
 
-	if [[ -z ${target} ]]; then
-		LOG "The SSID or BSSID is configured to be ignored."
-		return 0
-	fi
+  if [[ -z ${target} ]]; then
+    LOG "The SSID or BSSID is configured to be ignored."
+    return 0
+  fi
 
   local cur
   cur="$(CURRENT_LOCATION)"
@@ -156,8 +156,8 @@ LOAD_CONFIG() {
     fi
   done < "${CONFIG_FILE}"
 
-	# LOG "SSID to ignore: ${IGNORE_SSIDS[*]}"
-	# LOG "BSSID to ignore: ${IGNORE_BSSIDS[*]}"
+  # LOG "SSID to ignore: ${IGNORE_SSIDS[*]}"
+  # LOG "BSSID to ignore: ${IGNORE_BSSIDS[*]}"
 
   if (( errors > 0 )); then
     ERR "Found ${errors} syntax error(s) in ${CONFIG_FILE}. Faulty lines were ignored."
@@ -170,12 +170,12 @@ DECIDE_LOCATION() {
   # If BSSID is ignored
   if IN_ARRAY "${bssid}" "${IGNORE_BSSIDS[@]}"; then
     bssid=""
-		return 0
+    return 0
   fi
   # If SSID is ignored
   if IN_ARRAY "${ssid}" "${IGNORE_SSIDS[@]}"; then
     ssid=""
-		return 0
+    return 0
   fi
   # Prefer BSSID match
   if [[ -n "${bssid}" && -n "${MAP_BSSID[${bssid}]:-}" ]]; then
@@ -192,30 +192,30 @@ DECIDE_LOCATION() {
 }
 
 DETERMINE_COMMAND() {
-	local line=""
-	local ssid=""
-	local cmd=""
-	local i=0
+  local line=""
+  local ssid=""
+  local cmd=""
+  local i=0
 
-	for cmd in "${CHECK_SSID_COMMANDS[@]}"; do
-		LOG "Trying to find SSID/BSSID [Method #${i}]"
-		while IFS= read -r line; do
-			case "$line" in
-				SSID:*)  ssid="${line#SSID:}";;
-			esac
-		done < <(eval "${cmd}")
+  for cmd in "${CHECK_SSID_COMMANDS[@]}"; do
+    LOG "Trying to find SSID/BSSID [Method #${i}]"
+    while IFS= read -r line; do
+      case "$line" in
+        SSID:*)  ssid="${line#SSID:}";;
+      esac
+    done < <(eval "${cmd}")
 
-		if [[ -n ${ssid} && ${ssid} != "<redacted>" ]]; then
-			LOG "SSID found: ${ssid}"
-			LOG "Command: ${cmd}"
-			CHECK_SSID_COMMAND="${cmd}"
-			return;
-		fi
-		((i++))
-	done
+    if [[ -n ${ssid} && ${ssid} != "<redacted>" ]]; then
+      LOG "SSID found: ${ssid}"
+      LOG "Command: ${cmd}"
+      CHECK_SSID_COMMAND="${cmd}"
+      return;
+    fi
+    ((i++))
+  done
 
-	ERR "SSID/BSSID detection command not found."
-	exit 1
+  ERR "SSID/BSSID detection command not found."
+  exit 1
 }
 
 # Trap to allow clean messages
@@ -234,8 +234,8 @@ LOG "Arg 0=${0}"
 # [[ -n ${ZSH_PATCHLEVEL} ]] && LOG "ZSH_PATCHLEVEL=${ZSH_PATCHLEVEL}"
 LOG "WIFI_DEV=${WIFI_DEV}"
 if [[ -z ${WIFI_DEV} ]]; then
-	ERR "Can't determine Wi-Fi device."
-	exit 1
+  ERR "Can't determine Wi-Fi device."
+  exit 1
 fi
 
 DETERMINE_COMMAND
@@ -251,8 +251,8 @@ while :; do
     continue
   fi
 
-	[[ -z ${PREV_SSID} ]] && PREV_SSID="${cur_ssid}"
-	[[ -z ${PREV_BSSID} ]] && PREV_BSSID="${cur_bssid}"
+  [[ -z ${PREV_SSID} ]] && PREV_SSID="${cur_ssid}"
+  [[ -z ${PREV_BSSID} ]] && PREV_BSSID="${cur_bssid}"
 
   # Force location switch on first run, or when SSID/BSSID changes
   should_switch=0
